BookShopOnline/Controllers/QLChuDeController.cs
using BookShopOnline.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookShopOnline.Controllers
{
    public class QLChuDeController : Controller
    {
        // GET: QLChuDe
        private ModelBookShop _context = new ModelBookShop();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PartalChuDe()
        {
            var lstCD = _context.ChuDes.Take(10).OrderBy(x => x.TenChuDe).ToList();
            return PartialView(lstCD);
        }
    }
}

BookShopOnline/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
        <header class="row" style="height:110px">
            <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
                <div style="font-size: 3em;
                            font-family: Impact;
                            color: #d1179a;
                            text-shadow: 2px 2px 8px #09a4ba;">
                        BOOK SHOP ONLINE
                </div>
                <div style="color:#09a4ba; font-style:italic; border-top: 2px dotted gray; width:60%">Express - tkhuong 2024</div>
            </div>
            <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
                <img src="~/Images/logo_bookshop.png" height="100" style="float:right" />
            </div>
        </header>
        <nav class="row">
            <div class="col-12">
                <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
                    <div class="container-fluid">
                        @*<a class="navbar-brand" href="javascript:void(0)">Logo</a>*@
                        @Html.ActionLink("Trang chủ", "Index", "QLSach", new { @class="navbar-brand"})
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="mynavbar">
                            <ul class="navbar-nav me-auto">
                                <li class="nav-item">
                                    <a class="nav-link" href="javascript:void(0)">Link</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="javascript:void(0)">Link</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="javascript:void(0)">Link</a>
                                </li>
                            </ul>
                            <form class="d-flex">
                                <input class="form-control me-2" type="text" placeholder="Search">
                                <button class="btn btn-primary" type="button">Search</button>
                            </form>
                        </div>
                    </div>
                </nav>
            </div>
        </nav>

        <section class="row">
            <section class="col-md-9 col-lg-9 col-sm-12 col-xs-12">
                <div>
                    @RenderBody()
                </div>
            </section>
            <aside class="col-md-3 col-lg-3 col-sm-12 col-xs-12">
                @Html.Action("PartalChuDe", "QLChuDe")
                <div class="card">
                    <div class="card-header">NHÀ XUẤT BẢN</div>
                    <div class="card-body">Content</div>
                </div>
            </aside>
        </section>

        <footer class="row">
            <div class="col-12 card" style="margin-top:20px; text-align:center">
                <div class="card-footer">Copyright &copy; tkhuong 2024</div>                
            </div>
        </footer>

    </div>
</body>
</html>